obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.00, 0.00]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, data_type: LaserScan, topic:/differential_bot/laser/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: odom, data_type: PointCloud, topic: /particlecloud, marking: true, clearing: true}
