<?xml version='1.0'?>

<robot name="differential_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find slam_simulations)/urdf/differential_bot.gazebo"/>
    <link name="robot_footprint"></link>

    <joint name="robot_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="robot_footprint"/>
        <child link="chassis"/>
    </joint>

    <!-- Chassis Link -->

    <link name='chassis'>
        <pose>0 0 0.1 0 0 0</pose>

        <inertial>
            <mass value="15.0"/>
            <origin xyz="0.0 0 0" rpy=" 0 0 0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>

        <collision name='collision'>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <geometry>
                <box size=".4 .4 .1"/>
            </geometry>
        </collision>

        <visual name='chassis_visual'>
            <origin xyz="0 0 0" rpy=" 0 0 0"/>
            <geometry>
                <box size=".4 .4 .1"/>
            </geometry>
            <material name="black">
                <color rgba="0 0 0 1"/>
            </material>
        </visual>

        <collision name='back_caster_collision'>
            <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>

        <visual name='back_caster_visual'>
            <origin xyz="-0.15 0 -0.05" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </visual>

        <collision name='front_caster_collision'>
            <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <surface>
                <friction>
                    <ode>
                        <mu>0</mu>
                        <mu2>0</mu2>
                        <slip1>1.0</slip1>
                        <slip2>1.0</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>

        <visual name='front_caster_visual'>
            <origin xyz="0.15 0 -0.05" rpy=" 0 0 0"/>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
        </visual>

    </link>

    <!-- Left Wheel Link -->

    <link name='left_wheel'>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>

        <collision name='collision'>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
                <cylinder length="0.05" radius="0.1"/>
            </geometry>
        </collision>

        <visual name='wheel_visual'>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
                <cylinder length="0.05" radius="0.1"/>
            </geometry>
        </visual>
    </link>

    <!-- Right Wheel Link -->

    <link name='right_wheel'>
        <inertial>
            <mass value="5.0"/>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>

        <collision name='collision'>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
                <cylinder length="0.05" radius="0.1"/>
            </geometry>
        </collision>

        <visual name='wheel_visual'>
            <origin xyz="0.0 0 0" rpy=" 0 1.5707 1.5707"/>
            <geometry>
                <cylinder length="0.05" radius="0.1"/>
            </geometry>
        </visual>
    </link>

    <!-- Left and Right Wheel Joints -->
    <joint type="continuous" name="left_wheel_hinge">
        <origin xyz="0.0 0.25 0" rpy="0 0 0"/>
        <child link="left_wheel"/>
        <parent link="chassis"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000"/>
        <joint_properties damping="1.0" friction="1.0"/>
    </joint>

    <joint type="continuous" name="right_wheel_hinge">
        <origin xyz="0 -0.25 0" rpy="0 0 0"/>
        <child link="right_wheel"/>
        <parent link="chassis"/>
        <axis xyz="0 1 0" rpy="0 0 0"/>
        <limit effort="10000" velocity="1000"/>
        <joint_properties damping="1.0" friction="1.0"/>
    </joint>

<!-- ADDED -->
<!-- ADDED -->
<!-- ADDED -->

 <joint name="hokuyo_joint" type="fixed">
    <!-- <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/> -->
    <origin xyz="0.15 0 0.09" rpy="0 0 0"/> 
    <parent link="chassis"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://slam_simulations/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- DEPTH CAMERA DEPTH CAMERA DEPTH CAMERA DEPTH CAMERA DEPTH CAMERA DEPTH CAMERA -->
  

  <link name="camera">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                     iyy="0.001" iyz="0.0"
                     izz="0.001" />
        </inertial>

        <visual>
            <origin xyz=" 0 0 0 " rpy="0 0 0" />
            <geometry>
                <mesh filename="package://slam_simulations/meshes/kinect.dae"/>
            </geometry>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="0.0730 .2760 0.0720"/>
            </geometry>
        </collision>

    </link>

    <joint name="camera_depth_joint" type="fixed">
        <origin xyz="0 0.011 0" rpy="0 0 0" />
        <parent link="camera" />
        <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                     iyy="0.001" iyz="0.0"
                     izz="0.001" />
        </inertial>
    </link>

    <joint name="camera_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57" />
        <parent link="camera_depth_frame" />
        <child link="camera_depth_optical_frame" />
    </joint>

    <link name="camera_depth_optical_frame">
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>

    <joint name="camera_rgb_joint" type="fixed">
        <origin xyz="0 -0.012 0" rpy="0 0 0" />
        <parent link="camera" />
        <child link="camera_rgb_frame" />
    </joint>

    <link name="camera_rgb_frame">
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>

    <joint name="camera_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57" />
        <parent link="camera_rgb_frame" />
        <child link="camera_rgb_optical_frame" />
    </joint>

    <link name="camera_rgb_optical_frame">
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>

    <!-- Camera Joint -->
    <joint name="base_camera_joint" type="fixed">
        <origin xyz="0.22 0 0" rpy="0 -0.349 0" />
        <parent link="chassis" />
        <child link="camera" />
    </joint>

</robot>
